controller_list:
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - shoulder_3_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
